src/TicketBundle/Entity/ticket.php
<?php

namespace TicketBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use UserBundle\Entity\user;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * ticket
 *
 * @ORM\Table(name="ticket")
 * @ORM\Entity(repositoryClass="TicketBundle\Repository\ticketRepository")
 */
class ticket {

    public function __construct() {
        $this->dateDeadline = new \DateTime();

    }

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var bool $done
     *
     * @ORM\Column(name="done", type="boolean")
     */
    private $done = false;


    /**
     *
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\user")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $userCreated;


    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_creation", type="datetime", nullable=true)
     */
    private $dateCreation;

    /**
     * @var \DateTime
     *
     * @Assert\NotBlank(message="insert deadline")
     * @ORM\Column(name="date_deadline", type="datetime")
     */
    private $dateDeadline;

    /**
     * @var string
     *
     * @Assert\NotBlank(message="insert ticket name")
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @var int
     *
     * @Assert\Type(
     *      type="integer",
     *      message="points value given ({{value}}) is not a valid {{type}} type."
     * )
     * @Assert\NotBlank(message="insert number of sprint points")
     * @ORM\Column(name="number_points", type="integer")
     */
    private $numberPoints;

    /**
     * @var string
     *
     * @Assert\NotBlank(message="insert project in which ticket should belong")
     * @ORM\Column(name="project", type="string", length=255)
     */
    private $project;

    /**
     * @ORM\Column(name="slug", unique=true)
     * @Gedmo\Slug(fields={"id", "name",}, updatable=false)
     */
    private $slug;



    /* ----------------------------------------------------- */



    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set userCreated
     *
     * @param user $userCreated
     *
     * @return ticket
     */
    public function setUserCreated($userCreated)
    {
        $this->userCreated = $userCreated;

        return $this;
    }

    /**
     * Get userCreated
     *
     * @return user
     */
    public function getUserCreated()
    {
        return $this->userCreated;
    }

    /**
     * Set dateCreation
     *
     * @param \DateTime $dateCreation
     *
     * @return ticket
     */
    public function setDateCreation($dateCreation)
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    /**
     * Get dateCreation
     *
     * @return \DateTime
     */
    public function getDateCreation()
    {
        return $this->dateCreation;
    }

    /**
     * Set dateDeadline
     *
     * @param \DateTime $dateDeadline
     *
     * @return ticket
     */
    public function setDateDeadline($dateDeadline)
    {
        $this->dateDeadline = $dateDeadline;

        return $this;
    }

    /**
     * Get dateDeadline
     *
     * @return \DateTime
     */
    public function getDateDeadline()
    {
        return $this->dateDeadline;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return ticket
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return ticket
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set numberPoints
     *
     * @param integer $numberPoints
     *
     * @return ticket
     */
    public function setNumberPoints($numberPoints)
    {
        $this->numberPoints = $numberPoints;

        return $this;
    }

    /**
     * Get numberPoints
     *
     * @return int
     */
    public function getNumberPoints()
    {
        return $this->numberPoints;
    }

    /**
     * Set project
     *
     * @param string $project
     *
     * @return ticket
     */
    public function setProject($project)
    {
        $this->project = $project;

        return $this;
    }

    /**
     * Get project
     *
     * @return string
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * @return string
     */
    public function isDoneString()
    {
        if($this->done == true)
            return "task was completed.";
        else
            return "task in progress";
    }

    public function isDoneBoolean()
    {
        return $this->done;
    }

    /**
     * @param boolean $done
     */
    public function setDone($done)
    {
        $this->done = $done;
    }



    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    }
}

src/TicketBundle/Form/ticketType.php
<?php

namespace TicketBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use UserBundle\Entity\user;

class ticketType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
            ->add('submit', SubmitType::class, array('label'=>'submit'))
     //       ->add('userCreated', 'text')
//            ->add('userAssigned', 'text')
     /*       ->add('dateCreation', 'datetime') */ //handled from within database
            ->add('dateDeadline', 'datetime')
            ->add('name', 'text')
            ->add('description', 'text')
            ->add('numberPoints', 'integer')
            ->add('project');
          //  ->add('status');
    }

    public function buildEditForm(FormBuilderInterface $builder, array $options) {
//        $builder
//            ->add('submit', SubmitType::class, array('label'=>'submit'))
//          // ->add('userCreated.username', 'text')
////            ->add('userAssigned', 'text')
//            /*       ->add('dateCreation', 'datetime') */ //handled from within database
//            ->add('dateDeadline', 'datetime')
//            ->add('name', 'text')
//            ->add('description', 'text')
//            ->add('numberPoints', 'integer')
//            ->add('project');
//         //   ->add('status');
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'TicketBundle\Entity\ticket'
        ));
    }
}

src/TicketBundle/Controller/ticketController.php
<?php

namespace TicketBundle\Controller;

use Doctrine\ORM\EntityManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Session\Session;
use TicketBundle\Entity\ticket;
use TicketBundle\Form\ticketType;
use CustomMailerBundle\Controller\DefaultController;
use TicketBundle\Repository\ticketRepository;
use AestheticBundle\Containers\BootstrapNavbarElements;
use AestheticBundle\Containers\BootstrapNavbar;
use AestheticBundle\Containers\NavbarHelperElements;
/**
 * ticket controller.
 *
 */
class ticketController extends Controller
{
    private $session;

    /**
     * Lists all ticket entities.
     */
    public function indexAction() {
        /** @var EntityManager $em */
        $em = $this->getDoctrine()->getManager();

        /** @var \Doctrine\ORM\EntityRepository $repository */
        $repository = $em->getRepository('TicketBundle:ticket');


        if($this->get('security.context')->isGranted('ROLE_ADMIN')) {
            $upcomingTicketsVisible = $repository->getTicketsUpcomingAdmin();
            $overdueTicketsVisible = $repository->getTicketsOverdueAdmin();
            $doneTicketsVisible = $repository->getTicketsDoneAdmin();
        } else {
            $upcomingTicketsVisible = $repository->getTicketsUpcoming($this->getUser());
            $overdueTicketsVisible = $repository->getTicketsOverdue($this->getUser());
            $doneTicketsVisible = $repository->getTicketsDone($this->getUser());
        }

        $doneCount = count($doneTicketsVisible);
        $upcomingCount = count($upcomingTicketsVisible);
        $overdueCount = count($overdueTicketsVisible);

        if(($doneCount + $upcomingCount + $overdueCount) == 0)
            $percent = 0;
        else
            $percent = ( $doneCount / ($doneCount + $upcomingCount + $overdueCount) ) * 100;

        $progressbarText = "Tickets Completed: " . number_format($percent, 0) . "% (" . $doneCount . "/" . ($doneCount + $upcomingCount + $overdueCount) . ")";


        return $this->render('TicketBundle:Ticket:index.html.twig', array(
            'helper' => (new NavbarHelperElements())->createHelperIndex(),
            'navbarLeft' => (new BootstrapNavbar())->createNavbarIndexLeft(),
            'navbarRight' => (new BootstrapNavbar())->createNavbarStandardRight(),
            'progressbarText' => $progressbarText,
            'progressbarValue' => $percent,
            'completedTickets' => $doneTicketsVisible,
            'upcomingTickets' => $upcomingTicketsVisible,
            'overdueTickets' => $overdueTicketsVisible,
            'controllerAction' => 'indexAction()'
        ));
    }

    public function firstIndexAction() {
        $this->session = new Session();
        $this->session->getFlashBag()->add('flash_success', 'Good to see you back! See all of your tickets below...');
//        /** @var EntityManager $em */
//        $em = $this->getDoctrine()->getManager();
//
//        /** @var \Doctrine\ORM\EntityRepository $repository */
//        $repository = $em->getRepository('TicketBundle:ticket');
//
//
//        $upcomingTicketsVisible = $repository->findAllUpcomingTicketsUser($this->getUser());
//        $overdueTicketsVisible = $repository->findAllOverdueTicketsUser($this->getUser());
//
//
//        return $this->render('TicketBundle:Ticket:index.html.twig', array(
//            'helper' => (new NavbarHelperElements())->createHelperIndex(),
//            'navbarLeft' => (new BootstrapNavbar())->createNavbarIndexLeft(),
//            'navbarRight' => (new BootstrapNavbar())->createNavbarStandardRight(),
//            'upcomingTickets' => $upcomingTicketsVisible,
//            'overdueTickets' => $overdueTicketsVisible,
//            'controllerAction' => 'indexAction()'
//        ));
        return $this->indexAction();
    }



//    public function sortedAction() {
//    }




    public function showAction($slug) {

        $manager = $this->getDoctrine()->getManager();
        $ticket = $manager->getRepository('TicketBundle:ticket')->findOneBy(array('slug' => $slug));
        $form = $this->createDeleteForm($ticket);
        if(!$ticket) throw $this->createNotFoundException('Unable to find given ticket');


        return $this->render('TicketBundle:Ticket:show.html.twig', array(
            'helper' => (new NavbarHelperElements())->createHelperShow(),
            'navbarLeft' => (new BootstrapNavbar())->createNavbarShowLeft(),
            'navbarRight' => (new BootstrapNavbar())->createNavbarStandardRight(),
            'ticket' => $ticket,
            'delete_form' => $form->createView()
        ));
    }


    public function newAction(Request $request) {

        $ticket = new ticket();
        $form = $this->createForm(new ticketType(), $ticket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ticket->setUserCreated($this->getUser());
            $ticket->setDateCreation(new \DateTime());

            $em = $this->getDoctrine()->getManager();
            $em->persist($ticket);
            $em->flush();

            $this->session = new Session();
            $this->session->getFlashBag()
                ->add('flash_success', 'Congratulations on successfully creating a new ticket!');

            $this->get('custommailerservice')->sendNewTicketMail($this->getUser(), $ticket);

            return $this->redirectToRoute('ticketcrud_show', array('slug' => $ticket->getSlug()));
        }

        if($form->isSubmitted() && !$form->isValid()) {
            $this->session = new Session();
            $this->session->getFlashBag()
                ->add('flash_error', 'There are some errors in form data we have received. Please fix them.');
        }

        return $this->render('TicketBundle:Ticket:new.html.twig', array(
            'helper' => (new NavbarHelperElements())->createHelperNew(),
            'navbarLeft' => (new BootstrapNavbar())->createNavbarNewLeft(),
            'navbarRight' => (new BootstrapNavbar())->createNavbarStandardRight(),
            'ticket' => $ticket,
            'form' => $form->createView(),
        ));
    }


    /**
     * Displays a form to edit an existing ticket entity.
     *
     */
    public function editAction(Request $request, ticket $ticket)
    {
        $deleteForm = $this->createDeleteForm($ticket);
        $editForm = $this->createForm(new ticketType(), $ticket);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($ticket);
            $em->flush();
            $this->session = new Session();
            $this->session->getFlashBag()
                ->add('flash_success', 'Your ticket was succesfully altered and changes were saved. Your ticket now looks like this:');

            return $this->redirectToRoute('ticketcrud_show', array('slug' => $ticket->getSlug()));
        }
        else if ($editForm->isSubmitted() && !$editForm->isValid()) {
            $this->session = new Session();
            $this->session->getFlashBag()
                ->add('flash_error', 'Something went wrong with processing your edit. Try again, please!');
        }



        return $this->render('TicketBundle:Ticket:edit.html.twig', array(
            'helper' => (new NavbarHelperElements())->createHelperEdit(),
            'navbarLeft' => (new BootstrapNavbar())->createNavbarEditLeft(),
            'navbarRight' => (new BootstrapNavbar())->createNavbarStandardRight(),
            'ticket' => $ticket,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }


    /**
     * Deletes a ticket entity.
     *
     */
    public function deleteAction(Request $request, ticket $ticket)
    {
        $form = $this->createDeleteForm($ticket);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($ticket);
            $em->flush();
        }

        return $this->redirectToRoute('ticketcrud_index');
    }

    /**
     * Creates a form to delete a ticket entity.
     *
     * @param ticket $ticket The ticket entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(ticket $ticket)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('ticketcrud_delete', array('id' => $ticket->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }




    public function completionAction($id, $format) {
        $manager = $this->getDoctrine()->getManager();
        $ticket = $manager->getRepository('TicketBundle:ticket')->find($id);

        if(!$ticket) throw $this->createNotFoundException('ticket not found :c');

        $ticket->setDone(1);

        $manager->persist($ticket);
        $manager->flush();

        return $this->completionSet($ticket, $format);

    }

    public function unCompletionAction($id, $format) {
        $manager = $this->getDoctrine()->getManager();
        $ticket = $manager->getRepository('TicketBundle:ticket')->find($id);

        if(!$ticket) throw $this->createNotFoundException('ticket not found :c');

        $ticket->setDone(false);
        $manager->persist($ticket);
        $manager->flush();

        return $this->completionSet($ticket, $format);

    }

    public function completionSet(ticket $ticket, $format) {

        if ($format == 'json') {
            $json = array(
                'completed' => $ticket->isDoneBoolean()
            );
            return new JsonResponse($json);
        } else
            return $this->redirect($this->generateUrl('ticketcrud_show', array( 'slug' => $ticket->getSlug())));
    }

}

src/TicketBundle/Resources/views/Ticket/edit.html.twig
{% extends 'TicketBundle::layout.html.twig' %}

{% block body %}
    <section class="events">
        <h3>Here you can edit your ticket:</h3>
    </section>

    <section class="event-show event-edit">
        <article>
            <section>
                {{ form_start(edit_form) }}
                    {{ form_errors(edit_form) }}
                <h1>
                    <dr>ticket name:</dr>
                    <hr>
                </h1>
                    <dl>
                        <dt></dt>
                        <dd>
                            {{ form_errors(edit_form.name) }}
                            {{ form_widget(edit_form.name) }}
                        </dd>

                        <dt>description:</dt>
                        <dd>
                            {{ form_errors(edit_form.description) }}
                            {{ form_widget(edit_form.description) }}
                        </dd>

                        <dt>Deadline:</dt>
                        <dd>
                            {{ form_errors(edit_form.dateDeadline) }}
                            {{ form_widget(edit_form.dateDeadline) }}
                        </dd>

                        <dt>Project:</dt>
                        <dd>
                            {{ form_errors(edit_form.project) }}
                            {{ form_widget(edit_form.project) }}
                        </dd>

                        <dt>Sprint:</dt>
                        <dd>
                            {{ form_errors(edit_form.numberPoints) }}
                            {{ form_widget(edit_form.numberPoints) }}
                        </dd>

                    </dl>

                {{ form_end(edit_form) }}

                {{ form(delete_form) }}

            </section>
        </article>
    </section>
{% endblock %}

src/TicketBundle/Resources/views/Ticket/index.html.twig
{% extends 'TicketBundle::layout.html.twig' %}

{% block body %}


    <section class="events">

        <header id="menu">
                <h2>Your tickets in one place:</h2>

        </header>
        {#<div class="progress">#}
            {#<div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar"#}
                 {#aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width:40%">#}
                {#Tickets Completed: 40%#}
            {#</div>#}
        {#</div>#}

        <div class="progress">
            <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar"
                 aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width:{{ progressbarValue }}%">
                {{ progressbarText }}
            </div>
        </div>

        <hr>


        {% if upcomingTickets|length<1 %}

            <h3>No upcoming Tickets!</h3><br><br>

        {% else %}

            <h3>Upcoming Tickets:</h3><br><br>
            {% for ticket in upcomingTickets %}
                <article>
                    <section>
                        <div class="alert alert-warning fade in">
                        <h3>
                            <a href="{{ path('ticketcrud_show', {'slug': ticket.slug}) }}">{{ ticket.name }}</a>
                        </h3>
                        <dl>

                            <dt>Status:</dt>
                            <dd>To be done</dd>

                            <dt>Deadline:</dt>
                            <dd> {{ ticket.dateDeadline | date("Y-m-d H:i:s") }} </dd>

                            <dt>Project:</dt>
                            <dd>{{ ticket.project }}</dd>

                            <dt>Desc:</dt>
                            {% if ticket.description is null %}
                                <dd><i>(none given)</i></dd>
                            {% else %}
                                <dd>{{ ticket.description }}</dd>
                            {% endif %}

                            <dt>Owner:</dt>
                            <dd>{{ ticket.userCreated.username }}</dd>
                        </dl>
                        </div>
                    </section>
                </article>
            {% endfor %}
        {% endif %}

        <hr>
        {% if overdueTickets|length<1 %}

            <h3>No overdue Tickets!</h3><br><br>

        {% else %}

            <h3>Overdue Tickets:</h3><br><br>
            {% for ticket in overdueTickets %}
                <article>
                    <section>
                        <div class="alert alert-danger fade in">
                            <h3>
                                <a href="{{ path('ticketcrud_show', {'slug': ticket.slug}) }}">{{ ticket.name }}</a>
                            </h3>
                            <dl>
                                <dt>Status:</dt>
                                <dd>Overdue / needs attention</dd>

                                <dt>Deadline:</dt>
                                <dd> {{ ticket.dateDeadline | date("Y-m-d H:i:s") }} </dd>

                                <dt>Project:</dt>
                                <dd>{{ ticket.project }}</dd>

                                <dt>Desc:</dt>
                                {% if ticket.description is null %}
                                    <dd>(none given)</dd>
                                {% else %}
                                    <dd>{{ ticket.description }}</dd>
                                {% endif %}

                                <dt>Owner:</dt>
                                <dd>{{ ticket.userCreated.username }}</dd>

                            </dl>
                        </div>
                    </section>
                </article>
            {% endfor %}
        {% endif %}

        <hr>
        {% if completedTickets|length<1 %}

            <h3>No completed Tickets!</h3><br><br>

        {% else %}

            <h3>Completed Tickets:</h3><br><br>
            {% for ticket in completedTickets %}
                <article>
                    <section>
                        <div class="alert alert-success fade in">
                            <h3>
                                <a href="{{ path('ticketcrud_show', {'slug': ticket.slug}) }}">{{ ticket.name }}</a>
                            </h3>
                            <dl>
                                <dt>Status:</dt>
                                <dd>Overdue / needs attention</dd>

                                <dt>Deadline:</dt>
                                <dd> {{ ticket.dateDeadline | date("Y-m-d H:i:s") }} </dd>

                                <dt>Project:</dt>
                                <dd>{{ ticket.project }}</dd>

                                <dt>Desc:</dt>
                                {% if ticket.description is null %}
                                    <dd><i>(none given)</i></dd>
                                {% else %}
                                    <dd>{{ ticket.description }}</dd>
                                {% endif %}

                                <dt>Owner:</dt>
                                <dd>{{ ticket.userCreated.username }}</dd>

                            </dl>
                        </div>
                    </section>
                </article>
            {% endfor %}
        {% endif %}


    </section>
{% endblock %}

src/TicketBundle/Resources/views/Ticket/new.html.twig
{% extends 'TicketBundle::layout.html.twig' %}

{% block body %}

    <section class="events">
        <header id="menu">
            <h3>Here you can create a new one:</h3>
        </header>
    </section>


    <section class="event-show event-edit">
        <article>
            <section>
            {% if not form.vars.valid %}
            <div class="alert alert-danger fade in">
                Something is not right. Check your input, please... </br></hr>
                {% else %}
                <div class="alert alert-warning fade in">
                    Create a brand new ticket below: </br></hr>
                    {% endif %}


                {# the opening <form> tag #}
                {{ form_start(form) }}
                    {{ form_errors(form) }}
                    <h1>
                        <dt>ticket name:</dt>

                    </h1>

                <dd>
                    {{ form_errors(form.name) }}
                    {{ form_widget(form.name) }}
                </dd>

                    <dt>description:</dt>
                    <dd>
                        {{ form_errors(form.description) }}
                        {{ form_widget(form.description) }}
                    </dd>

                    <dt>Deadline:</dt>
                    <dd>
                        {{ form_errors(form.dateDeadline) }}
                        {{ form_widget(form.dateDeadline) }}
                    </dd>


                    <dt>Project:</dt>
                    <dd>
                        {{ form_errors(form.project) }}
                        {{ form_widget(form.project) }}
                    </dd>

                    <dt>Sprint:</dt>
                    <dd>
                        {{ form_errors(form.numberPoints) }}
                        {{ form_widget(form.numberPoints) }}
                    </dd>


                {# the closing </form> tag #}
                {{ form_end(form) }}

                </div></div>
            </section>
        </article>
    </section>
{% endblock %}

src/TicketBundle/Resources/views/Ticket/show.html.twig
{% extends 'TicketBundle::layout.html.twig' %}

{% block body %}

    <section class="events">
        <header id="menu">
            <h3>See everything about it:</h3>
        </header>
    </section>

    <section class="event-show">
        <article>
            <section>
                <h1>
                    {{ ticket.name }}
                </h1>

                <hr>
                <dl>
                    <dt>description:</dt>
                    <dd>{{ ticket.description }}</dd>

                    <dt>Creation:</dt>
                    <dd>{{ ticket.dateCreation | date("Y-m-d H:i:s") }}</dd>

                    <dt>Deadline:</dt>
                    <dd>{{ ticket.dateDeadline | date("Y-m-d H:i:s") }}</dd>

                    <dt>Reporter:</dt>
                    <dd>{{ ticket.userCreated.username }} </dd>

                    {#<dt>Assignee:</dt>#}
                    {#<dd>{{ ticket.userAssigned }} </dd>#}

                    <dt>Project:</dt>
                    <dd>{{ ticket.project }} </dd>

                    <dt>Sprint:</dt>
                    <dd>{{ ticket.numberPoints }} </dd>

                    <dt>Status:</dt>
                    <dd>
                        {{ ticket.doneString }}
                    </dd>

                    <br>

                    {% if ticket.doneBoolean %}
                        <a href = "{{ path('ticketcrud_uncompletion', {id: ticket.id}) }}"
                           button type="button" class="btn btn-danger pull-right js-completion-toggle">SET IN PROGRESS</a>
                    {% else %}
                        <a href = "{{ path('ticketcrud_completion', {id: ticket.id}) }}"
                           button type="button" class="btn btn-success pull-right js-completion-toggle">SET COMPLETED</a>
                    {% endif %}


                    <hr>
                    {#<a href = "{{ path('ticketcrud_index') }}"#}
                       {#button type="button" class="btn btn-danger pull-left">REJECTED</a>#}
                    <a href = "{{ path('ticketcrud_delete', {'id': ticket.id}) }}"
                       button type="button" class="btn btn-warning pull-right">delete</a>
                    <a href = "{{ path('ticketcrud_edit', {'id': ticket.id}) }}"
                       button type="button" class="btn btn-warning pull-right">edit</a>
                    <a href = "{{ path('ticketcrud_index') }}"
                       button type="button" class="btn btn-primary pull-right">back</a>
                    <hr>
                </dl>
            </section>
        </article>
    </section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script>
        $(document).ready(function() {
            $('.js-completion-toggle').on('click', function(e) {
                e.preventDefault();

                var $anchor = $(this);
                var url = $(this).attr('href')+'.json';

                $.post(url, null, function(data) {
                    if (data.completed) {
                        var message = 'Task is completed. Congratulations!';
                        $anchor.after('<span class="label label-success pull-right">&#10004; '+message+'</span>');
                    } else {
                        var message = 'Task is in progress now. Be sure to meet deadline!';
                        $anchor.after('<span class="label label-danger pull-right">&#10004; '+message+'</span>');
                    }
                    $anchor.hide();
                });
            });
        });


    </script>

{% endblock %}